[versions]
agp = "8.7.0"
kotlin = "1.9.20"
coreKtx = "1.13.1"
appcompat = "1.7.0"
activity = "1.9.0"
shagenerator = "1.1"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
shagenerator = { module = "com.github.karmokarjay:SHAGenerator", version.ref = "shagenerator" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
android-library = { id = "com.android.library", version.ref = "agp" }

